# global configs
global:
  scrape_interval: 15s
  evaluation_interval: 1m
  scrape_timeout: 10s

scrape_configs:
  - job_name: "prometheus"
    metrics_path: /metrics
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "gRPC"
    metrics_path: /metrics
    static_configs:
      - targets: ["localhost:9091"]